name: dog_breed_classifier
description: A Flutter app for dog breed classification
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Material Design
  cupertino_icons: ^1.0.2
  
  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.7
  
  # TensorFlow Lite
  tflite_flutter: ^0.11.0
  
  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/